#!/usr/bin/env Rscript

## ============================================================================
## Reproducibility script: paired inference for the aggregation gap D_B
## "When Does a Pathway Score Preserve a Mediated Effect?"
##
## Purpose
##   Finite-sample evaluation of the paired influence-function standard error
##   for D_B = DE_Z - DE_M, compared with a deliberately naive standard error
##   that ignores Cov(DE_Z, DE_M).
##
## Data
##   No external data are required.
##
## Output
##   gap_inference_results_R.csv
##
## Notes
##   The published extended-manuscript table was originally generated by the
##   Python reference implementation using NumPy's RNG. This R port implements
##   the same population construction, estimands, estimators, Monte Carlo cells,
##   and seed value. Because R and NumPy use different random-number streams,
##   Monte Carlo summaries will be close rather than bit-for-bit identical.
##
##   If gap_inference_results.csv (the archived Python reference table) is in
##   the working directory, this script also prints a side-by-side comparison.
##
## Requirements
##   Base R only.
## ============================================================================

options(stringsAsFactors = FALSE, scipen = 999)

SEED  <- 16092026L
NREP  <- as.integer(Sys.getenv("SIM_REPS", "800"))
RHO   <- 0.35
D_ALT <- 0.20

## ---- Helpers ----------------------------------------------------------------

ar1_cov <- function(p, rho = RHO) {
  idx <- seq_len(p)
  rho ^ abs(outer(idx, idx, "-"))
}

population_setup <- function(p) {
  Sigma <- ar1_cov(p, RHO)
  B <- matrix(rep(1 / sqrt(p), p), ncol = 1L)

  ## Smooth, non-collinear exposure effects.
  idx <- seq_len(p)
  alpha <- 0.22 * exp(-idx / (0.55 * p)) * ifelse(idx %% 3L == 0L, -0.75, 1.0)

  ## Oblique projection and omitted gap direction
  ## u = (I - P_B)' alpha.
  K <- solve(crossprod(B, Sigma %*% B))
  P_B <- B %*% K %*% crossprod(B, Sigma)
  u <- drop(crossprod(diag(p) - P_B, alpha))

  ## Null: beta lies in col(B), so D_B = 0 exactly. Scale to IE_M = 0.35.
  bvec <- drop(B)
  beta0 <- bvec * (0.35 / sum(alpha * bvec))

  ## Alternative: add exactly D_ALT units in the omitted gap direction.
  beta1 <- beta0 + (D_ALT / sum(u^2)) * u

  D0 <- sum(u * beta0)
  D1 <- sum(u * beta1)
  IE0 <- sum(alpha * beta0)

  ## Algebraic checks should be at machine precision.
  stopifnot(abs(D0) < 1e-12,
            abs(D1 - D_ALT) < 1e-12,
            abs(IE0 - 0.35) < 1e-12)

  list(Sigma = Sigma, b = bvec, alpha = alpha,
       beta0 = beta0, beta1 = beta1, u = u,
       D0 = D0, D1 = D1)
}

## Coefficient on A and its observation-level influence contribution from
## regression Y ~ A + controls. The influence function is
##     IF_i = v_i e_i / E(v^2),
## where v is the residual from projecting A on the controls.
ols_a_if <- function(y, a, controls) {
  n <- length(y)
  controls <- as.matrix(controls)

  X <- cbind(`(Intercept)` = 1, A = a, controls)
  fit_y <- lm.fit(x = X, y = y)
  theta <- unname(fit_y$coefficients[2L])
  e <- fit_y$residuals

  C <- cbind(`(Intercept)` = 1, controls)
  fit_a <- lm.fit(x = C, y = a)
  v <- fit_a$residuals
  den <- mean(v^2)

  if (den <= .Machine$double.eps)
    stop("Exposure residual variance is numerically zero.")

  list(theta = theta, IF = v * e / den)
}

one_rep <- function(n, setup, alternative = FALSE) {
  p <- length(setup$alpha)
  beta <- if (alternative) setup$beta1 else setup$beta0
  D_true <- sum(setup$u * beta)

  q <- 2L
  W <- matrix(rnorm(n * q), nrow = n, ncol = q)
  A <- 0.30 * W[, 1L] - 0.20 * W[, 2L] + rnorm(n)

  idx <- seq_len(p)
  Gamma <- cbind(0.12 * sin(idx / 3),
                 0.10 * cos(idx / 4))

  ## R's chol() returns U with t(U) %*% U = Sigma. For row-wise N(0,I)
  ## draws E0, E0 %*% U therefore has covariance Sigma.
  U <- chol(setup$Sigma)
  E <- matrix(rnorm(n * p), nrow = n, ncol = p) %*% U

  M <- A %o% setup$alpha + W %*% t(Gamma) + E

  tau <- 0.25
  eta <- c(0.20, -0.15)
  Y <- tau * A + drop(M %*% beta) + drop(W %*% eta) + rnorm(n)
  Z <- drop(M %*% setup$b)

  full <- ols_a_if(Y, A, cbind(W, M))
  agg  <- ols_a_if(Y, A, cbind(W, Z))

  D_hat <- agg$theta - full$theta
  IF_diff <- agg$IF - full$IF

  se_paired <- sqrt(var(IF_diff) / n)
  se_naive  <- sqrt(var(agg$IF) / n + var(full$IF) / n)

  c(D_true = D_true,
    D_hat = D_hat,
    se = se_paired,
    se_naive = se_naive)
}

summarize_cell <- function(vals, n, p, scenario) {
  vals <- as.data.frame(vals)
  D_true <- vals$D_true[1L]
  zcrit <- qnorm(0.975)

  cover <- mean(vals$D_hat - zcrit * vals$se <= D_true &
                  D_true <= vals$D_hat + zcrit * vals$se)
  reject <- mean(abs(vals$D_hat / vals$se) > zcrit)

  cover_naive <- mean(vals$D_hat - zcrit * vals$se_naive <= D_true &
                        D_true <= vals$D_hat + zcrit * vals$se_naive)
  reject_naive <- mean(abs(vals$D_hat / vals$se_naive) > zcrit)

  data.frame(
    n = n,
    p = p,
    scenario = scenario,
    D_true = D_true,
    bias = mean(vals$D_hat - D_true),
    empirical_sd = sd(vals$D_hat),
    mean_se = mean(vals$se),
    coverage = cover,
    rejection = reject,
    mean_width = 2 * zcrit * mean(vals$se),
    naive_mean_width = 2 * zcrit * mean(vals$se_naive),
    naive_coverage = cover_naive,
    naive_rejection = reject_naive,
    nrep = NREP,
    check.names = FALSE
  )
}

run_cell <- function(n, p, alternative, setup) {
  scenario <- if (alternative) "alternative" else "null"
  message(sprintf("Running n=%d, p=%d, %s (%d replicates)",
                  n, p, scenario, NREP))

  vals <- t(replicate(NREP, one_rep(n, setup, alternative), simplify = TRUE))
  vals <- as.data.frame(vals)
  names(vals) <- c("D_true", "D_hat", "se", "se_naive")
  summarize_cell(vals, n, p, scenario)
}

## ---- Monte Carlo study ------------------------------------------------------

set.seed(SEED)

settings <- data.frame(
  n = c(300L, 600L, 600L, 1000L),
  p = c(12L, 12L, 30L, 30L)
)

out <- vector("list", nrow(settings) * 2L)
pos <- 1L

for (ii in seq_len(nrow(settings))) {
  n_i <- settings$n[ii]
  p_i <- settings$p[ii]
  setup <- population_setup(p_i)

  for (alt in c(FALSE, TRUE)) {
    out[[pos]] <- run_cell(n_i, p_i, alt, setup)
    pos <- pos + 1L
  }
}

res <- do.call(rbind, out)
row.names(res) <- NULL

write.csv(res, "gap_inference_results_R.csv", row.names = FALSE)

cat("\nPaired gap-inference simulation results (R):\n")
print(res, digits = 4, row.names = FALSE)

## ---- Optional comparison with archived Python reference ---------------------

ref_file <- "gap_inference_results.csv"
if (file.exists(ref_file)) {
  ref <- read.csv(ref_file, stringsAsFactors = FALSE)
  key <- c("n", "p", "scenario")

  cmp <- merge(res, ref, by = key, suffixes = c("_R", "_Py"), sort = FALSE)
  metrics <- c("bias", "empirical_sd", "mean_se", "coverage", "rejection",
               "mean_width", "naive_mean_width", "naive_coverage",
               "naive_rejection")

  for (nm in metrics) {
    cmp[[paste0(nm, "_diff")]] <- cmp[[paste0(nm, "_R")]] -
      cmp[[paste0(nm, "_Py")]]
  }

  keep <- c(key,
            "D_true_R", "D_true_Py",
            unlist(lapply(metrics, function(nm)
              c(paste0(nm, "_R"), paste0(nm, "_Py"), paste0(nm, "_diff")))))
  keep <- keep[keep %in% names(cmp)]

  write.csv(cmp[, keep, drop = FALSE],
            "gap_inference_R_vs_python.csv", row.names = FALSE)

  cat("\nComparison with archived Python reference:\n")
  short <- cmp[, c(key, "coverage_R", "coverage_Py",
                   "rejection_R", "rejection_Py",
                   "mean_width_R", "mean_width_Py",
                   "naive_mean_width_R", "naive_mean_width_Py")]
  print(short, digits = 4, row.names = FALSE)
  cat("\nWrote gap_inference_R_vs_python.csv\n")
}

## ---- Manuscript-ready rows --------------------------------------------------

fmt <- function(x, d = 3) formatC(x, format = "f", digits = d)
cat("\nManuscript-ready rows:\n")
for (i in seq_len(nrow(res))) {
  sc <- if (res$scenario[i] == "null") "$D_B=0$" else "$D_B=0.20$"
  cat(sprintf("%d & %d & %s & %s & %s & %s & %s & %s & %s (%s)\\\\\n",
              res$n[i], res$p[i], sc,
              fmt(res$bias[i]), fmt(res$empirical_sd[i]), fmt(res$mean_se[i]),
              fmt(res$coverage[i]), fmt(res$rejection[i]),
              fmt(res$mean_width[i]), fmt(res$naive_mean_width[i])))
}

cat("\nSaved: gap_inference_results_R.csv\n")
cat("Seed:", SEED, "  Replicates per cell:", NREP, "\n")
cat("R version:", R.version.string, "\n")
